


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Leistung" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "budget" double precision
);


ALTER TABLE "public"."Leistung" OWNER TO "postgres";


COMMENT ON TABLE "public"."Leistung" IS 'Leistung die einem Pflegegrad zugeordnet ist';



ALTER TABLE "public"."Leistung" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Leistung_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Leistungsberechtiger_Leistungselemente" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "leistungselement_id" bigint,
    "leistungsberechtigter_id" bigint
);


ALTER TABLE "public"."Leistungsberechtiger_Leistungselemente" OWNER TO "postgres";


ALTER TABLE "public"."Leistungsberechtiger_Leistungselemente" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Leistungsberechtiger_Leistungselemente_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Leistungsberechtigter" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "firstname" character varying,
    "lastname" character varying,
    "pflegegrad" smallint,
    "leistung_id" bigint
);


ALTER TABLE "public"."Leistungsberechtigter" OWNER TO "postgres";


COMMENT ON TABLE "public"."Leistungsberechtigter" IS 'Tabelle für Leistungsberechtigte und deren Pflegegrade mit Bescheiden';



ALTER TABLE "public"."Leistungsberechtigter" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Leistungsberechtigter_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Leistungselement" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "budget" double precision
);


ALTER TABLE "public"."Leistungselement" OWNER TO "postgres";


COMMENT ON TABLE "public"."Leistungselement" IS 'Leistungselemente einer Leistung';



ALTER TABLE "public"."Leistungselement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Leistungselement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Leistung"
    ADD CONSTRAINT "Leistung_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Leistungsberechtiger_Leistungselemente"
    ADD CONSTRAINT "Leistungsberechtiger_Leistungselemente_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Leistungsberechtigter"
    ADD CONSTRAINT "Leistungsberechtigter_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Leistungselement"
    ADD CONSTRAINT "Leistungselement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Leistungsberechtiger_Leistungselemente"
    ADD CONSTRAINT "Leistungsberechtiger_Leistungsele_leistungsberechtigter_id_fkey" FOREIGN KEY ("leistungsberechtigter_id") REFERENCES "public"."Leistungsberechtigter"("id");



ALTER TABLE ONLY "public"."Leistungsberechtiger_Leistungselemente"
    ADD CONSTRAINT "Leistungsberechtiger_Leistungselemente_leistungselement_id_fkey" FOREIGN KEY ("leistungselement_id") REFERENCES "public"."Leistung"("id");



ALTER TABLE ONLY "public"."Leistungsberechtigter"
    ADD CONSTRAINT "Leistungsberechtigter_leistung_id_fkey" FOREIGN KEY ("leistung_id") REFERENCES "public"."Leistung"("id");



ALTER TABLE "public"."Leistung" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Leistungsberechtiger_Leistungselemente" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Leistungsberechtigter" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Leistungselement" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."Leistung" TO "anon";
GRANT ALL ON TABLE "public"."Leistung" TO "authenticated";
GRANT ALL ON TABLE "public"."Leistung" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Leistung_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Leistung_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Leistung_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Leistungsberechtiger_Leistungselemente" TO "anon";
GRANT ALL ON TABLE "public"."Leistungsberechtiger_Leistungselemente" TO "authenticated";
GRANT ALL ON TABLE "public"."Leistungsberechtiger_Leistungselemente" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Leistungsberechtiger_Leistungselemente_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Leistungsberechtiger_Leistungselemente_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Leistungsberechtiger_Leistungselemente_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Leistungsberechtigter" TO "anon";
GRANT ALL ON TABLE "public"."Leistungsberechtigter" TO "authenticated";
GRANT ALL ON TABLE "public"."Leistungsberechtigter" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Leistungsberechtigter_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Leistungsberechtigter_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Leistungsberechtigter_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Leistungselement" TO "anon";
GRANT ALL ON TABLE "public"."Leistungselement" TO "authenticated";
GRANT ALL ON TABLE "public"."Leistungselement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Leistungselement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Leistungselement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Leistungselement_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


